<a href="https://colab.research.google.com/github/mariyamakda24-a11y/MariyaMakda_MachineLearning_92400588025/blob/main/covid_toy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
#from sklearn.compose import ColumnTransformer
#from sklearn.pipeline import Pipeline
#from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest,f_regression,f_classif
#from sklearn.decomposition import PCA

In [2]:
df=pd.read_csv("covid_toy.csv")

display(df.head())

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
print(df.dtypes)

age            int64
gender        object
fever        float64
cough         object
city          object
has_covid     object
dtype: object

In [4]:
df.columns

Index(['age', 'gender', 'fever', 'cough', 'city', 'has_covid'], dtype='object')

In [5]:
#To automatically find numeric columns
numeric_columns=df.select_dtypes(include=np.number).columns

print("Numeric Columns:")
print(numeric_columns)

#origin is often represented by numbers such as 1,2,3
#so technically pandas may identify it as numeric
#even though it represents categories.

Numeric Columns:
Index(['age', 'fever'], dtype='object')

In [6]:
#To automatically find categorical columns:
categorical_columns=df.select_dtypes(include="object").columns

print("Categorical Columns:")
print(categorical_columns)

Categorical Columns:
Index(['gender', 'cough', 'city', 'has_covid'], dtype='object')

In [7]:
#First Check missing values:
print(df.isnull().sum())

#Auto-MPG commonly represents missing horsepower values using?.
#So first convert ? into missing value:

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [8]:
df["fever"]=pd.to_numeric(df["fever"].replace("?",np.nan),errors="coerce")

df["fever"]=df["fever"].replace(np.nan,df["fever"].mean())

print(df.isnull().sum())

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [9]:
scaler=MinMaxScaler().set_output(transform="pandas")

scaled_data=scaler.fit_transform(df[numeric_columns])

scaled_data.head()

        age     fever
0  0.696203  0.833333
1  0.278481  0.333333
2  0.468354  0.500000
3  0.329114  0.000000
4  0.759494  0.500000

In [10]:
# Define X and y
X = df.drop("age", axis=1)
y = df["age"]

# Select the numeric columns
X_numeric = X.select_dtypes(include=np.number)

# Select the best feature (since we only have 1 numeric feature: 'fever')
selector = SelectKBest(
    score_func=f_regression,
    k=1
).set_output(transform="pandas")

X_selected = selector.fit_transform(X_numeric, y)

print(X_selected.head())

   fever
0  103.0
1  100.0
2  101.0
3   98.0
4  101.0